{{- $password := required "database.password must be provided" .Values.database.password }}
{{- $postgresHost := printf "%s-postgres" (include "trade-journal.fullname" .) }}
{{- $databaseURL := printf "postgres://%s:%s@%s:%v/%s?sslmode=disable"
      (.Values.database.username | urlquery)
      ($password | urlquery)
      $postgresHost
      .Values.database.port
      (.Values.database.name | urlquery)
}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trade-journal.secretName" . }}
  labels:
    {{- include "trade-journal.labels" . | nindent 4 }}

type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.username | quote }}
  POSTGRES_PASSWORD: {{ $password | quote }}
  POSTGRES_DB: {{ .Values.database.name | quote }}
  DATABASE_URL: {{ $databaseURL | quote }}
  GOOSE_DRIVER: postgres
  GOOSE_DBSTRING: {{ $databaseURL | quote }}

